### ISSUE TITLE
Crear consultas de base de datos para los servicios de la vista de perfil del alumno

### ISSUE THREAD

**Issue by onzalo** [ElAsistente/elasistente#1]
**Como...** un desarrollador del asistente
**Quiero...** crear consultas de BBDD
**Para...** crear los endpoints a ser consumidos por el front-end

**Alcance**
Preparar consultas para el Vista Perfil del Alumno:
- [x] Promedio con aplazo del alumno actual
- [x] Promedio sin aplazo del alumno actual
- [x] Porcentaje de la Carrera
- [x] Cantidad de Materias Aprobadas
- [x] Cantidad de Materias Regulares
- [x] Cantidad de materias aprobadas por área
- [ ] Lista de Materias Aprobadas (nombre, nota, nivel, area)
- [ ] Lista de Materias Regulares (nombre, nota, nivel, area)

**Fuera de Alcance**
- Crear los endpoints.
- Realizar cambios en el front-end.
- Realizar cambios en la estructura de la base de datos.
