### ISSUE TITLE
Agregar endpoints para Vista Perfil del Alumno

### ISSUE THREAD

**Issue by onzalo** [ElAsistente/elasistente#3]
**Como...** un desarrollador del asistente
**Quiero...** crear endpoints
**Para...** para ser consumidos por la vista de perfil del alumno

**Alcance**
Implementar enpoints diseñados en #2 con las consultas creadas en #1. 
- [x] Promedio con aplazo del alumno actual
- [x] Promedio sin aplazo del alumno actual
- [x] Porcentaje de la Carrera
- [x] Cantidad de Materias Aprobadas
- [x] Cantidad de Materias Regulares
- [x] Cantidad de materias aprobadas por área
- [ ] Lista de Materias Aprobadas (nombre, nota, nivel, area)
- [ ] Lista de Materias Regulares (nombre, nota, nivel, area)

**Fuera de Alcance**
- Realizar cambios en la UI.
- Realizar cambios en la BBDD.
